server:
  port: ${SERVER_PORT:7801}
  ssl:
    enabled: false

spring:
  application:
    name: btc-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://145.223.22.73:30002/
    userId: root
    password: live@Bottomhalf_001
    database: btc_meets


  # LiveKit configuration
livekit:
  api:
    key: APIJByNUPVKqDS8
    secret: mcv0eMRL9uSw3fAna0jkDjxs4ZKBvpAM5WV9k3fOvk4B

fierhub:
  configuration-service:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJhbnkiLCJuYmYiOjE3NjA3MjIzMzcsImV4cCI6MTc5MzQ3MTM0MCwiaWF0IjoxNzYwNzIyMzM3fQ.xrUyENjoJydC0mTBgOsxawQ3m42uPNhL4dvz5a1PLC4_tid11_fid=6
    file-name: token_1757862221025
    use-filter: true
  authorize:
    routes:
      - /api/auth/authenticateUser
      - /api/auth
      - /api/conference/token
      - /api/meeting/validateMeeting