# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build & Push Docker Image
      run: |
        echo "Displaying token value: ${{ secrets.REPOSITORY_USERNAME }}"
        docker build \
          --build-arg REPOSITORY_USERNAME=${{ secrets.REPOSITORY_USERNAME }} \
          --build-arg REPOSITORY_TOKEN=${{ secrets.REPOSITORY_TOKEN }} \
          -t bottomhalflimited/conf.svc.manager:dev-2509 .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push bottomhalflimited/conf.svc.manager:dev-2509        

    - name: SSH to Remote server and deploy
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Apply new changes
      run: |
        echo "Deleting existing Kubernetes resources"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "microk8s kubectl delete -f /root/kube.ws/confeet/main-service/conf-manager-deploy.yml"
        
        echo "Applying new Kubernetes configuration"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "microk8s kubectl apply -f /root/kube.ws/confeet/main-service/conf-manager-deploy.yml"

    - name: cleanup
      run: |
        echo "Cleaning up SSH credentials"
        rm -rf ~/.ssh